# Generated by Django 3.2.13 on 2022-06-16 06:19

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pubdate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='postimage',
            name='image',
            field=models.ImageField(upload_to=blog.models.post_directory_path),
        ),
    ]
